export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const LOAD_TODOLIST = "LOAD_TODOLIST"
export const CHECK_DONE = "CHECK_DONE"